services:
  backend:
    build: 
        context: ./server
        dockerfile: Dockerfile
    volumes:
      - .:/var/www/server
    command: bash run.sh
    # restart: always
    user: root
    ports:
      - "8000:8000"
    env_file:
      - server/.env.prod
   

  frontend:
    build: ./client
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev

  