services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        command: ./server bash run.sh
        restart: always
        user: root
        volumes:
            - .:/var/www/server
        ports:
            - 8000:8000
        env_file:
            - server/.env

    frontend:
       build: ./client
       ports:
          - "4173:4173"
       volumes:
        - .:/app
        - /app/node_modules
       environment:
         - NODE_ENV=development
  

