services:
  backend:
    build: ./server
    volumes:
      - .:/var/www/server
    command: bash run.sh
    restart: always
    user: root
    ports:
      - 8000:8000
    env_file:
      - ./server/.env.prod
    depends_on:
      - database

  frontend:
    build: ./client
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev

  database:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=1234
    ports: 
      - 5432:5432
