global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: audql-server
    scrape_interval: 5s
    metrics_path: /metrics/
    static_configs:
      - targets: [server:8000]

  - job_name: kafka
    static_configs:
      - targets: [kafka-exporter:9308]
