services:
    pearmonie:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash run.sh
        restart: always
        user: root
        volumes:
            - .:/var/www/pearmonie
        ports:
            - 8000:8000
        env_file:
            - ./.env
  

