services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash run.sh
        # restart: always
        user: root
        volumes:
            - .:/var/www/server
        ports:
            - 8000:8000
        environment:
            - DEBUG=1
        env_file:
            - ./.env
   

  