# Generated by Django 5.1.1 on 2024-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='8Kiep4skowcEFbS', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=150),
        ),
    ]
