# Generated by Django 5.1 on 2024-08-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='T0rH8AFz2hmWmIA', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
