# Generated by Django 5.2.17 on 2026-09-30 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_queuejob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sms_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='push_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='queuejob',
            name='kind',
            field=models.CharField(choices=[('search.index', 'Search index'), ('search.delete', 'Search delete'), ('query.generate', 'Generate query'), ('query.audio', 'Transcribe audio query'), ('email.activation', 'Activation email'), ('email.password_reset', 'Password reset email'), ('notification.send', 'Send notification'), ('orders.export', 'Export orders')], max_length=40),
        ),
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(default='web', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_device',
                'ordering': ['created'],
            },
        ),
    ]
