# Generated by Django 5.1 on 2024-08-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_user_phone_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='BfDPMDaZTPLCo2d', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
